-- Moodle++ Database Schema (Normalized to 4NF)
-- 18 Entities with Constraints and Foreign Keys

CREATE TABLE IF NOT EXISTS User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Bio TEXT,
    GitHubLink VARCHAR(255),
    LinkedInLink VARCHAR(255),
    CONSTRAINT chk_User_Email CHECK (Email LIKE '%@%')
);

CREATE TABLE IF NOT EXISTS Role (
    RoleID INT AUTO_INCREMENT PRIMARY KEY,
    RoleName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Course (
    CourseID INT AUTO_INCREMENT PRIMARY KEY,
    CourseCode VARCHAR(50) NOT NULL UNIQUE,
    Title VARCHAR(255) NOT NULL,
    Description TEXT
);

CREATE TABLE IF NOT EXISTS Rubric (
    RubricID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Department VARCHAR(100),
    Description TEXT
);

CREATE TABLE IF NOT EXISTS UserPhoto (
    UserID INT,
    PhotoURL VARCHAR(255),
    PRIMARY KEY (UserID, PhotoURL),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Batch (
    BatchID INT AUTO_INCREMENT PRIMARY KEY,
    BatchName VARCHAR(100) NOT NULL,
    CourseID INT NOT NULL,
    UNIQUE (CourseID, BatchName),
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ResourceCategory (
    CategoryID INT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(100) NOT NULL,
    CourseID INT NOT NULL,
    UNIQUE (CourseID, CategoryName),
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ClassSession (
    SessionID INT AUTO_INCREMENT PRIMARY KEY,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    RoomLocation VARCHAR(100),
    BatchID INT NOT NULL,
    CONSTRAINT chk_ClassSession_Time CHECK (EndTime > StartTime),
    FOREIGN KEY (BatchID) REFERENCES Batch(BatchID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Assignment (
    AssignmentID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Deadline DATETIME NOT NULL,
    FormatRequired VARCHAR(50),
    CourseID INT NOT NULL,
    RubricID INT,
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (RubricID) REFERENCES Rubric(RubricID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Resource (
    ResourceID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    FileURL VARCHAR(500) NOT NULL,
    UploadedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CategoryID INT NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES ResourceCategory(CategoryID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Submission (
    SubmissionID INT AUTO_INCREMENT PRIMARY KEY,
    SubmissionTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    ContentData TEXT NOT NULL,
    AssignmentID INT NOT NULL,
    UserID INT NOT NULL,
    FOREIGN KEY (AssignmentID) REFERENCES Assignment(AssignmentID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Question (
    QuestionID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Body TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CourseID INT NOT NULL,
    UserID INT NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Answer (
    AnswerID INT AUTO_INCREMENT PRIMARY KEY,
    Body TEXT NOT NULL,
    Upvotes INT DEFAULT 0,
    IsOfficialAnswer BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    QuestionID INT NOT NULL,
    UserID INT NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES Question(QuestionID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AnswerUpvote (
    AnswerID INT NOT NULL,
    UserID INT NOT NULL,
    PRIMARY KEY (AnswerID, UserID),
    FOREIGN KEY (AnswerID) REFERENCES Answer(AnswerID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Notification (
    NotificationID INT AUTO_INCREMENT PRIMARY KEY,
    Message TEXT NOT NULL,
    Type VARCHAR(50),
    IsRead BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Evaluation (
    SubmissionID INT PRIMARY KEY,
    Score DECIMAL(5,2) NOT NULL,
    Feedback TEXT,
    UserID INT NOT NULL,
    CONSTRAINT chk_Evaluation_Score CHECK (Score >= 0),
    FOREIGN KEY (SubmissionID) REFERENCES Submission(SubmissionID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Prerequisite (
    CourseID INT NOT NULL,
    RequiredCourseID INT NOT NULL,
    MinPassingGrade DECIMAL(5,2),
    PRIMARY KEY (CourseID, RequiredCourseID),
    CONSTRAINT chk_Prereq_Self CHECK (CourseID != RequiredCourseID),
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (RequiredCourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Attendance (
    SessionID INT NOT NULL,
    UserID INT NOT NULL,
    Status VARCHAR(20) NOT NULL,
    PRIMARY KEY (SessionID, UserID),
    CONSTRAINT chk_Attendance_Status CHECK (Status IN ('Present', 'Absent', 'Excused')),
    FOREIGN KEY (SessionID) REFERENCES ClassSession(SessionID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Enrollment (
    EnrollmentID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    CourseID INT NOT NULL,
    RoleID INT NOT NULL,
    BatchID INT,
    UNIQUE (UserID, CourseID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE RESTRICT,
    FOREIGN KEY (BatchID) REFERENCES Batch(BatchID) ON DELETE SET NULL
);
