-- Drop all tables in reverse dependency order

DROP TABLE IF EXISTS Enrollment;
DROP TABLE IF EXISTS Attendance;
DROP TABLE IF EXISTS Prerequisite;
DROP TABLE IF EXISTS Evaluation;
DROP TABLE IF EXISTS Notification;
DROP TABLE IF EXISTS AnswerUpvote;
DROP TABLE IF EXISTS Answer;
DROP TABLE IF EXISTS Question;
DROP TABLE IF EXISTS Submission;
DROP TABLE IF EXISTS Resource;
DROP TABLE IF EXISTS Assignment;
DROP TABLE IF EXISTS ClassSession;
DROP TABLE IF EXISTS ResourceCategory;
DROP TABLE IF EXISTS Batch;
DROP TABLE IF EXISTS UserPhoto;
DROP TABLE IF EXISTS Rubric;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS User;
