-- Clear all seed data

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Enrollment;
TRUNCATE TABLE Attendance;
TRUNCATE TABLE Prerequisite;
TRUNCATE TABLE Evaluation;
TRUNCATE TABLE Notification;
TRUNCATE TABLE AnswerUpvote;
TRUNCATE TABLE Answer;
TRUNCATE TABLE Question;
TRUNCATE TABLE Submission;
TRUNCATE TABLE Resource;
TRUNCATE TABLE Assignment;
TRUNCATE TABLE ClassSession;
TRUNCATE TABLE ResourceCategory;
TRUNCATE TABLE Batch;
TRUNCATE TABLE UserPhoto;
TRUNCATE TABLE Rubric;
TRUNCATE TABLE Course;
TRUNCATE TABLE Role;
TRUNCATE TABLE User;
SET FOREIGN_KEY_CHECKS = 1;
