// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAssignment = `-- name: CreateAssignment :execresult
INSERT INTO Assignment (Title, Description, Deadline, FormatRequired, CourseID, RubricID)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAssignmentParams struct {
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Deadline       time.Time      `json:"deadline"`
	Formatrequired sql.NullString `json:"formatrequired"`
	Courseid       int32          `json:"courseid"`
	Rubricid       sql.NullInt32  `json:"rubricid"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAssignment,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.Formatrequired,
		arg.Courseid,
		arg.Rubricid,
	)
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM Assignment WHERE AssignmentID = ?
`

func (q *Queries) DeleteAssignment(ctx context.Context, assignmentid int32) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, assignmentid)
	return err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT a.AssignmentID, a.Title, a.Description, a.Deadline, a.FormatRequired, a.CourseID, a.RubricID,
       r.Title AS RubricTitle, r.Department AS RubricDepartment, r.Description AS RubricDescription,
       c.CourseCode, c.Title AS CourseTitle
FROM Assignment a
JOIN Course c ON a.CourseID = c.CourseID
LEFT JOIN Rubric r ON a.RubricID = r.RubricID
WHERE a.AssignmentID = ? LIMIT 1
`

type GetAssignmentByIDRow struct {
	Assignmentid      int32          `json:"assignmentid"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	Deadline          time.Time      `json:"deadline"`
	Formatrequired    sql.NullString `json:"formatrequired"`
	Courseid          int32          `json:"courseid"`
	Rubricid          sql.NullInt32  `json:"rubricid"`
	Rubrictitle       sql.NullString `json:"rubrictitle"`
	Rubricdepartment  sql.NullString `json:"rubricdepartment"`
	Rubricdescription sql.NullString `json:"rubricdescription"`
	Coursecode        string         `json:"coursecode"`
	Coursetitle       string         `json:"coursetitle"`
}

func (q *Queries) GetAssignmentByID(ctx context.Context, assignmentid int32) (GetAssignmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentByID, assignmentid)
	var i GetAssignmentByIDRow
	err := row.Scan(
		&i.Assignmentid,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.Formatrequired,
		&i.Courseid,
		&i.Rubricid,
		&i.Rubrictitle,
		&i.Rubricdepartment,
		&i.Rubricdescription,
		&i.Coursecode,
		&i.Coursetitle,
	)
	return i, err
}

const getPendingAssignmentsForStudent = `-- name: GetPendingAssignmentsForStudent :many
SELECT 
    c.CourseCode,
    c.Title AS CourseTitle,
    a.AssignmentID,
    a.Title AS AssignmentName,
    a.Deadline,
    a.FormatRequired
FROM Assignment a
JOIN Course c ON a.CourseID = c.CourseID
JOIN Enrollment e ON c.CourseID = e.CourseID
LEFT JOIN Submission s ON a.AssignmentID = s.AssignmentID AND e.UserID = s.UserID
WHERE e.UserID = ?
  AND s.SubmissionID IS NULL
ORDER BY a.Deadline ASC
`

type GetPendingAssignmentsForStudentRow struct {
	Coursecode     string         `json:"coursecode"`
	Coursetitle    string         `json:"coursetitle"`
	Assignmentid   int32          `json:"assignmentid"`
	Assignmentname string         `json:"assignmentname"`
	Deadline       time.Time      `json:"deadline"`
	Formatrequired sql.NullString `json:"formatrequired"`
}

func (q *Queries) GetPendingAssignmentsForStudent(ctx context.Context, userid int32) ([]GetPendingAssignmentsForStudentRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingAssignmentsForStudent, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingAssignmentsForStudentRow{}
	for rows.Next() {
		var i GetPendingAssignmentsForStudentRow
		if err := rows.Scan(
			&i.Coursecode,
			&i.Coursetitle,
			&i.Assignmentid,
			&i.Assignmentname,
			&i.Deadline,
			&i.Formatrequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingStudentsForAssignment = `-- name: GetPendingStudentsForAssignment :many
SELECT 
    c.CourseCode,
    a.Title AS AssignmentName,
    a.Deadline,
    u.UserID,
    u.FirstName,
    u.LastName,
    u.Email
FROM Assignment a
JOIN Course c ON a.CourseID = c.CourseID
JOIN Enrollment e ON c.CourseID = e.CourseID
JOIN Role r ON e.RoleID = r.RoleID 
JOIN User u ON e.UserID = u.UserID
LEFT JOIN Submission s ON a.AssignmentID = s.AssignmentID AND u.UserID = s.UserID
WHERE a.AssignmentID = ?
  AND r.RoleName = 'Student'
  AND s.SubmissionID IS NULL
ORDER BY u.LastName ASC
`

type GetPendingStudentsForAssignmentRow struct {
	Coursecode     string    `json:"coursecode"`
	Assignmentname string    `json:"assignmentname"`
	Deadline       time.Time `json:"deadline"`
	Userid         int32     `json:"userid"`
	Firstname      string    `json:"firstname"`
	Lastname       string    `json:"lastname"`
	Email          string    `json:"email"`
}

// Case Study Query 2: Students enrolled in course who have not submitted for this assignment
func (q *Queries) GetPendingStudentsForAssignment(ctx context.Context, assignmentid int32) ([]GetPendingStudentsForAssignmentRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingStudentsForAssignment, assignmentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingStudentsForAssignmentRow{}
	for rows.Next() {
		var i GetPendingStudentsForAssignmentRow
		if err := rows.Scan(
			&i.Coursecode,
			&i.Assignmentname,
			&i.Deadline,
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingStudentsForCourse = `-- name: GetPendingStudentsForCourse :many
SELECT 
    c.CourseCode,
    a.Title AS AssignmentName,
    a.Deadline,
    u.UserID,
    u.FirstName,
    u.LastName,
    u.Email
FROM Assignment a
JOIN Course c ON a.CourseID = c.CourseID
JOIN Enrollment e ON c.CourseID = e.CourseID
JOIN Role r ON e.RoleID = r.RoleID 
JOIN User u ON e.UserID = u.UserID
LEFT JOIN Submission s ON a.AssignmentID = s.AssignmentID AND u.UserID = s.UserID
WHERE c.CourseID = ?
  AND r.RoleName = 'Student'
  AND s.SubmissionID IS NULL
ORDER BY a.Deadline ASC, u.LastName ASC
`

type GetPendingStudentsForCourseRow struct {
	Coursecode     string    `json:"coursecode"`
	Assignmentname string    `json:"assignmentname"`
	Deadline       time.Time `json:"deadline"`
	Userid         int32     `json:"userid"`
	Firstname      string    `json:"firstname"`
	Lastname       string    `json:"lastname"`
	Email          string    `json:"email"`
}

func (q *Queries) GetPendingStudentsForCourse(ctx context.Context, courseid int32) ([]GetPendingStudentsForCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingStudentsForCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingStudentsForCourseRow{}
	for rows.Next() {
		var i GetPendingStudentsForCourseRow
		if err := rows.Scan(
			&i.Coursecode,
			&i.Assignmentname,
			&i.Deadline,
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByCourse = `-- name: ListAssignmentsByCourse :many
SELECT a.AssignmentID, a.Title, a.Description, a.Deadline, a.FormatRequired, a.CourseID, a.RubricID,
       r.Title AS RubricTitle, r.Department AS RubricDepartment
FROM Assignment a
LEFT JOIN Rubric r ON a.RubricID = r.RubricID
WHERE a.CourseID = ?
ORDER BY a.Deadline ASC
`

type ListAssignmentsByCourseRow struct {
	Assignmentid     int32          `json:"assignmentid"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Deadline         time.Time      `json:"deadline"`
	Formatrequired   sql.NullString `json:"formatrequired"`
	Courseid         int32          `json:"courseid"`
	Rubricid         sql.NullInt32  `json:"rubricid"`
	Rubrictitle      sql.NullString `json:"rubrictitle"`
	Rubricdepartment sql.NullString `json:"rubricdepartment"`
}

func (q *Queries) ListAssignmentsByCourse(ctx context.Context, courseid int32) ([]ListAssignmentsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentsByCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsByCourseRow{}
	for rows.Next() {
		var i ListAssignmentsByCourseRow
		if err := rows.Scan(
			&i.Assignmentid,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.Formatrequired,
			&i.Courseid,
			&i.Rubricid,
			&i.Rubrictitle,
			&i.Rubricdepartment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :exec
UPDATE Assignment
SET Title = ?, Description = ?, Deadline = ?, FormatRequired = ?, RubricID = ?
WHERE AssignmentID = ?
`

type UpdateAssignmentParams struct {
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Deadline       time.Time      `json:"deadline"`
	Formatrequired sql.NullString `json:"formatrequired"`
	Rubricid       sql.NullInt32  `json:"rubricid"`
	Assignmentid   int32          `json:"assignmentid"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, updateAssignment,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.Formatrequired,
		arg.Rubricid,
		arg.Assignmentid,
	)
	return err
}
