// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createClassSession = `-- name: CreateClassSession :execresult
INSERT INTO ClassSession (StartTime, EndTime, RoomLocation, BatchID)
VALUES (?, ?, ?, ?)
`

type CreateClassSessionParams struct {
	Starttime    time.Time      `json:"starttime"`
	Endtime      time.Time      `json:"endtime"`
	Roomlocation sql.NullString `json:"roomlocation"`
	Batchid      int32          `json:"batchid"`
}

func (q *Queries) CreateClassSession(ctx context.Context, arg CreateClassSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createClassSession,
		arg.Starttime,
		arg.Endtime,
		arg.Roomlocation,
		arg.Batchid,
	)
}

const getSessionAttendance = `-- name: GetSessionAttendance :many
SELECT a.SessionID, a.UserID, a.Status,
       u.FirstName, u.LastName, u.Email
FROM Attendance a
JOIN User u ON a.UserID = u.UserID
WHERE a.SessionID = ?
ORDER BY u.LastName ASC
`

type GetSessionAttendanceRow struct {
	Sessionid int32  `json:"sessionid"`
	Userid    int32  `json:"userid"`
	Status    string `json:"status"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
}

func (q *Queries) GetSessionAttendance(ctx context.Context, sessionid int32) ([]GetSessionAttendanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionAttendance, sessionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionAttendanceRow{}
	for rows.Next() {
		var i GetSessionAttendanceRow
		if err := rows.Scan(
			&i.Sessionid,
			&i.Userid,
			&i.Status,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT s.SessionID, s.StartTime, s.EndTime, s.RoomLocation, s.BatchID,
       b.BatchName, b.CourseID
FROM ClassSession s
JOIN Batch b ON s.BatchID = b.BatchID
WHERE s.SessionID = ? LIMIT 1
`

type GetSessionByIDRow struct {
	Sessionid    int32          `json:"sessionid"`
	Starttime    time.Time      `json:"starttime"`
	Endtime      time.Time      `json:"endtime"`
	Roomlocation sql.NullString `json:"roomlocation"`
	Batchid      int32          `json:"batchid"`
	Batchname    string         `json:"batchname"`
	Courseid     int32          `json:"courseid"`
}

func (q *Queries) GetSessionByID(ctx context.Context, sessionid int32) (GetSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, sessionid)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.Sessionid,
		&i.Starttime,
		&i.Endtime,
		&i.Roomlocation,
		&i.Batchid,
		&i.Batchname,
		&i.Courseid,
	)
	return i, err
}

const getUserAttendanceInCourse = `-- name: GetUserAttendanceInCourse :many
SELECT s.SessionID, s.StartTime, s.EndTime, s.RoomLocation, b.BatchName,
       IFNULL(att.Status, 'Unmarked') AS AttendanceStatus
FROM ClassSession s
JOIN Batch b ON s.BatchID = b.BatchID
JOIN Enrollment e ON (e.CourseID = b.CourseID AND (e.BatchID IS NULL OR e.BatchID = b.BatchID))
LEFT JOIN Attendance att ON (att.SessionID = s.SessionID AND att.UserID = e.UserID)
WHERE b.CourseID = ? AND e.UserID = ?
ORDER BY s.StartTime ASC
`

type GetUserAttendanceInCourseParams struct {
	Courseid int32 `json:"courseid"`
	Userid   int32 `json:"userid"`
}

type GetUserAttendanceInCourseRow struct {
	Sessionid        int32          `json:"sessionid"`
	Starttime        time.Time      `json:"starttime"`
	Endtime          time.Time      `json:"endtime"`
	Roomlocation     sql.NullString `json:"roomlocation"`
	Batchname        string         `json:"batchname"`
	Attendancestatus interface{}    `json:"attendancestatus"`
}

func (q *Queries) GetUserAttendanceInCourse(ctx context.Context, arg GetUserAttendanceInCourseParams) ([]GetUserAttendanceInCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAttendanceInCourse, arg.Courseid, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAttendanceInCourseRow{}
	for rows.Next() {
		var i GetUserAttendanceInCourseRow
		if err := rows.Scan(
			&i.Sessionid,
			&i.Starttime,
			&i.Endtime,
			&i.Roomlocation,
			&i.Batchname,
			&i.Attendancestatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAttendanceSummary = `-- name: GetUserAttendanceSummary :one
SELECT 
    COUNT(s.SessionID) AS TotalSessions,
    SUM(CASE WHEN att.Status = 'Present' THEN 1 ELSE 0 END) AS PresentCount,
    SUM(CASE WHEN att.Status = 'Absent' THEN 1 ELSE 0 END) AS AbsentCount,
    SUM(CASE WHEN att.Status = 'Excused' THEN 1 ELSE 0 END) AS ExcusedCount
FROM ClassSession s
JOIN Batch b ON s.BatchID = b.BatchID
JOIN Enrollment e ON (e.CourseID = b.CourseID AND (e.BatchID IS NULL OR e.BatchID = b.BatchID))
LEFT JOIN Attendance att ON (att.SessionID = s.SessionID AND att.UserID = e.UserID)
WHERE b.CourseID = ? AND e.UserID = ?
`

type GetUserAttendanceSummaryParams struct {
	Courseid int32 `json:"courseid"`
	Userid   int32 `json:"userid"`
}

type GetUserAttendanceSummaryRow struct {
	Totalsessions int64       `json:"totalsessions"`
	Presentcount  interface{} `json:"presentcount"`
	Absentcount   interface{} `json:"absentcount"`
	Excusedcount  interface{} `json:"excusedcount"`
}

func (q *Queries) GetUserAttendanceSummary(ctx context.Context, arg GetUserAttendanceSummaryParams) (GetUserAttendanceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAttendanceSummary, arg.Courseid, arg.Userid)
	var i GetUserAttendanceSummaryRow
	err := row.Scan(
		&i.Totalsessions,
		&i.Presentcount,
		&i.Absentcount,
		&i.Excusedcount,
	)
	return i, err
}

const listSessionsByBatch = `-- name: ListSessionsByBatch :many
SELECT s.SessionID, s.StartTime, s.EndTime, s.RoomLocation, s.BatchID,
       b.BatchName, b.CourseID
FROM ClassSession s
JOIN Batch b ON s.BatchID = b.BatchID
WHERE s.BatchID = ?
ORDER BY s.StartTime ASC
`

type ListSessionsByBatchRow struct {
	Sessionid    int32          `json:"sessionid"`
	Starttime    time.Time      `json:"starttime"`
	Endtime      time.Time      `json:"endtime"`
	Roomlocation sql.NullString `json:"roomlocation"`
	Batchid      int32          `json:"batchid"`
	Batchname    string         `json:"batchname"`
	Courseid     int32          `json:"courseid"`
}

func (q *Queries) ListSessionsByBatch(ctx context.Context, batchid int32) ([]ListSessionsByBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByBatch, batchid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByBatchRow{}
	for rows.Next() {
		var i ListSessionsByBatchRow
		if err := rows.Scan(
			&i.Sessionid,
			&i.Starttime,
			&i.Endtime,
			&i.Roomlocation,
			&i.Batchid,
			&i.Batchname,
			&i.Courseid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByCourse = `-- name: ListSessionsByCourse :many
SELECT s.SessionID, s.StartTime, s.EndTime, s.RoomLocation, s.BatchID,
       b.BatchName, b.CourseID
FROM ClassSession s
JOIN Batch b ON s.BatchID = b.BatchID
WHERE b.CourseID = ?
ORDER BY s.StartTime ASC
`

type ListSessionsByCourseRow struct {
	Sessionid    int32          `json:"sessionid"`
	Starttime    time.Time      `json:"starttime"`
	Endtime      time.Time      `json:"endtime"`
	Roomlocation sql.NullString `json:"roomlocation"`
	Batchid      int32          `json:"batchid"`
	Batchname    string         `json:"batchname"`
	Courseid     int32          `json:"courseid"`
}

func (q *Queries) ListSessionsByCourse(ctx context.Context, courseid int32) ([]ListSessionsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByCourseRow{}
	for rows.Next() {
		var i ListSessionsByCourseRow
		if err := rows.Scan(
			&i.Sessionid,
			&i.Starttime,
			&i.Endtime,
			&i.Roomlocation,
			&i.Batchid,
			&i.Batchname,
			&i.Courseid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttendance = `-- name: RecordAttendance :exec
INSERT INTO Attendance (SessionID, UserID, Status)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE Status = VALUES(Status)
`

type RecordAttendanceParams struct {
	Sessionid int32  `json:"sessionid"`
	Userid    int32  `json:"userid"`
	Status    string `json:"status"`
}

func (q *Queries) RecordAttendance(ctx context.Context, arg RecordAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, recordAttendance, arg.Sessionid, arg.Userid, arg.Status)
	return err
}
