// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package db

import (
	"context"
	"database/sql"
)

const createBatch = `-- name: CreateBatch :execresult
INSERT INTO Batch (BatchName, CourseID)
VALUES (?, ?)
`

type CreateBatchParams struct {
	Batchname string `json:"batchname"`
	Courseid  int32  `json:"courseid"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBatch, arg.Batchname, arg.Courseid)
}

const deleteBatch = `-- name: DeleteBatch :exec
DELETE FROM Batch WHERE BatchID = ?
`

func (q *Queries) DeleteBatch(ctx context.Context, batchid int32) error {
	_, err := q.db.ExecContext(ctx, deleteBatch, batchid)
	return err
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT BatchID, BatchName, CourseID
FROM Batch
WHERE BatchID = ? LIMIT 1
`

func (q *Queries) GetBatchByID(ctx context.Context, batchid int32) (Batch, error) {
	row := q.db.QueryRowContext(ctx, getBatchByID, batchid)
	var i Batch
	err := row.Scan(&i.Batchid, &i.Batchname, &i.Courseid)
	return i, err
}

const listBatchesByCourse = `-- name: ListBatchesByCourse :many
SELECT BatchID, BatchName, CourseID
FROM Batch
WHERE CourseID = ?
ORDER BY BatchName ASC
`

func (q *Queries) ListBatchesByCourse(ctx context.Context, courseid int32) ([]Batch, error) {
	rows, err := q.db.QueryContext(ctx, listBatchesByCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Batch{}
	for rows.Next() {
		var i Batch
		if err := rows.Scan(&i.Batchid, &i.Batchname, &i.Courseid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
