// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
	"database/sql"
)

const addCoursePrerequisite = `-- name: AddCoursePrerequisite :exec
INSERT INTO Prerequisite (CourseID, RequiredCourseID, MinPassingGrade)
VALUES (?, ?, ?)
`

type AddCoursePrerequisiteParams struct {
	Courseid         int32          `json:"courseid"`
	Requiredcourseid int32          `json:"requiredcourseid"`
	Minpassinggrade  sql.NullString `json:"minpassinggrade"`
}

func (q *Queries) AddCoursePrerequisite(ctx context.Context, arg AddCoursePrerequisiteParams) error {
	_, err := q.db.ExecContext(ctx, addCoursePrerequisite, arg.Courseid, arg.Requiredcourseid, arg.Minpassinggrade)
	return err
}

const createCourse = `-- name: CreateCourse :execresult
INSERT INTO Course (CourseCode, Title, Description)
VALUES (?, ?, ?)
`

type CreateCourseParams struct {
	Coursecode  string         `json:"coursecode"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourse, arg.Coursecode, arg.Title, arg.Description)
}

const deleteCoursePrerequisite = `-- name: DeleteCoursePrerequisite :exec
DELETE FROM Prerequisite WHERE CourseID = ? AND RequiredCourseID = ?
`

type DeleteCoursePrerequisiteParams struct {
	Courseid         int32 `json:"courseid"`
	Requiredcourseid int32 `json:"requiredcourseid"`
}

func (q *Queries) DeleteCoursePrerequisite(ctx context.Context, arg DeleteCoursePrerequisiteParams) error {
	_, err := q.db.ExecContext(ctx, deleteCoursePrerequisite, arg.Courseid, arg.Requiredcourseid)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT CourseID, CourseCode, Title, Description
FROM Course
WHERE CourseID = ? LIMIT 1
`

func (q *Queries) GetCourseByID(ctx context.Context, courseid int32) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByID, courseid)
	var i Course
	err := row.Scan(
		&i.Courseid,
		&i.Coursecode,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getCoursePrerequisites = `-- name: GetCoursePrerequisites :many
SELECT p.CourseID, p.RequiredCourseID, p.MinPassingGrade,
       c.CourseCode AS RequiredCourseCode, c.Title AS RequiredCourseTitle
FROM Prerequisite p
JOIN Course c ON p.RequiredCourseID = c.CourseID
WHERE p.CourseID = ?
`

type GetCoursePrerequisitesRow struct {
	Courseid            int32          `json:"courseid"`
	Requiredcourseid    int32          `json:"requiredcourseid"`
	Minpassinggrade     sql.NullString `json:"minpassinggrade"`
	Requiredcoursecode  string         `json:"requiredcoursecode"`
	Requiredcoursetitle string         `json:"requiredcoursetitle"`
}

func (q *Queries) GetCoursePrerequisites(ctx context.Context, courseid int32) ([]GetCoursePrerequisitesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCoursePrerequisites, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursePrerequisitesRow{}
	for rows.Next() {
		var i GetCoursePrerequisitesRow
		if err := rows.Scan(
			&i.Courseid,
			&i.Requiredcourseid,
			&i.Minpassinggrade,
			&i.Requiredcoursecode,
			&i.Requiredcoursetitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT CourseID, CourseCode, Title, Description
FROM Course
ORDER BY CourseCode ASC
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.Courseid,
			&i.Coursecode,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByUser = `-- name: ListCoursesByUser :many
SELECT c.CourseID, c.CourseCode, c.Title, c.Description
FROM Course c
JOIN Enrollment e ON e.CourseID = c.CourseID
WHERE e.UserID = ?
ORDER BY c.CourseCode ASC
`

func (q *Queries) ListCoursesByUser(ctx context.Context, userid int32) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCoursesByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.Courseid,
			&i.Coursecode,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
