// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package db

import (
	"context"
	"database/sql"
)

const checkPrerequisiteGrade = `-- name: CheckPrerequisiteGrade :one
SELECT AVG(e.Score) as AvgScore
FROM Evaluation e
JOIN Submission s ON e.SubmissionID = s.SubmissionID
JOIN Assignment a ON s.AssignmentID = a.AssignmentID
WHERE s.UserID = ? AND a.CourseID = ?
`

type CheckPrerequisiteGradeParams struct {
	Userid   int32 `json:"userid"`
	Courseid int32 `json:"courseid"`
}

func (q *Queries) CheckPrerequisiteGrade(ctx context.Context, arg CheckPrerequisiteGradeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, checkPrerequisiteGrade, arg.Userid, arg.Courseid)
	var avgscore interface{}
	err := row.Scan(&avgscore)
	return avgscore, err
}

const enrollUser = `-- name: EnrollUser :execresult
INSERT INTO Enrollment (UserID, CourseID, RoleID, BatchID)
VALUES (?, ?, ?, ?)
`

type EnrollUserParams struct {
	Userid   int32         `json:"userid"`
	Courseid int32         `json:"courseid"`
	Roleid   int32         `json:"roleid"`
	Batchid  sql.NullInt32 `json:"batchid"`
}

func (q *Queries) EnrollUser(ctx context.Context, arg EnrollUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, enrollUser,
		arg.Userid,
		arg.Courseid,
		arg.Roleid,
		arg.Batchid,
	)
}

const getEnrollmentByID = `-- name: GetEnrollmentByID :one
SELECT EnrollmentID, UserID, CourseID, RoleID, BatchID
FROM Enrollment
WHERE EnrollmentID = ? LIMIT 1
`

func (q *Queries) GetEnrollmentByID(ctx context.Context, enrollmentid int32) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentByID, enrollmentid)
	var i Enrollment
	err := row.Scan(
		&i.Enrollmentid,
		&i.Userid,
		&i.Courseid,
		&i.Roleid,
		&i.Batchid,
	)
	return i, err
}

const getEnrollmentsByCourse = `-- name: GetEnrollmentsByCourse :many
SELECT e.EnrollmentID, e.UserID, e.CourseID, e.RoleID, e.BatchID,
       u.FirstName, u.LastName, u.Email,
       r.RoleName, b.BatchName
FROM Enrollment e
JOIN User u ON e.UserID = u.UserID
JOIN Role r ON e.RoleID = r.RoleID
LEFT JOIN Batch b ON e.BatchID = b.BatchID
WHERE e.CourseID = ?
ORDER BY r.RoleID ASC, u.LastName ASC
`

type GetEnrollmentsByCourseRow struct {
	Enrollmentid int32          `json:"enrollmentid"`
	Userid       int32          `json:"userid"`
	Courseid     int32          `json:"courseid"`
	Roleid       int32          `json:"roleid"`
	Batchid      sql.NullInt32  `json:"batchid"`
	Firstname    string         `json:"firstname"`
	Lastname     string         `json:"lastname"`
	Email        string         `json:"email"`
	Rolename     string         `json:"rolename"`
	Batchname    sql.NullString `json:"batchname"`
}

func (q *Queries) GetEnrollmentsByCourse(ctx context.Context, courseid int32) ([]GetEnrollmentsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnrollmentsByCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnrollmentsByCourseRow{}
	for rows.Next() {
		var i GetEnrollmentsByCourseRow
		if err := rows.Scan(
			&i.Enrollmentid,
			&i.Userid,
			&i.Courseid,
			&i.Roleid,
			&i.Batchid,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Rolename,
			&i.Batchname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentsByUser = `-- name: GetEnrollmentsByUser :many
SELECT e.EnrollmentID, e.UserID, e.CourseID, e.RoleID, e.BatchID,
       c.CourseCode, c.Title AS CourseTitle, c.Description AS CourseDescription,
       r.RoleName, b.BatchName
FROM Enrollment e
JOIN Course c ON e.CourseID = c.CourseID
JOIN Role r ON e.RoleID = r.RoleID
LEFT JOIN Batch b ON e.BatchID = b.BatchID
WHERE e.UserID = ?
ORDER BY c.CourseCode ASC
`

type GetEnrollmentsByUserRow struct {
	Enrollmentid      int32          `json:"enrollmentid"`
	Userid            int32          `json:"userid"`
	Courseid          int32          `json:"courseid"`
	Roleid            int32          `json:"roleid"`
	Batchid           sql.NullInt32  `json:"batchid"`
	Coursecode        string         `json:"coursecode"`
	Coursetitle       string         `json:"coursetitle"`
	Coursedescription sql.NullString `json:"coursedescription"`
	Rolename          string         `json:"rolename"`
	Batchname         sql.NullString `json:"batchname"`
}

func (q *Queries) GetEnrollmentsByUser(ctx context.Context, userid int32) ([]GetEnrollmentsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnrollmentsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnrollmentsByUserRow{}
	for rows.Next() {
		var i GetEnrollmentsByUserRow
		if err := rows.Scan(
			&i.Enrollmentid,
			&i.Userid,
			&i.Courseid,
			&i.Roleid,
			&i.Batchid,
			&i.Coursecode,
			&i.Coursetitle,
			&i.Coursedescription,
			&i.Rolename,
			&i.Batchname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEnrollmentInCourse = `-- name: GetUserEnrollmentInCourse :one
SELECT e.EnrollmentID, e.UserID, e.CourseID, e.RoleID, e.BatchID, r.RoleName
FROM Enrollment e
JOIN Role r ON e.RoleID = r.RoleID
WHERE e.UserID = ? AND e.CourseID = ?
LIMIT 1
`

type GetUserEnrollmentInCourseParams struct {
	Userid   int32 `json:"userid"`
	Courseid int32 `json:"courseid"`
}

type GetUserEnrollmentInCourseRow struct {
	Enrollmentid int32         `json:"enrollmentid"`
	Userid       int32         `json:"userid"`
	Courseid     int32         `json:"courseid"`
	Roleid       int32         `json:"roleid"`
	Batchid      sql.NullInt32 `json:"batchid"`
	Rolename     string        `json:"rolename"`
}

func (q *Queries) GetUserEnrollmentInCourse(ctx context.Context, arg GetUserEnrollmentInCourseParams) (GetUserEnrollmentInCourseRow, error) {
	row := q.db.QueryRowContext(ctx, getUserEnrollmentInCourse, arg.Userid, arg.Courseid)
	var i GetUserEnrollmentInCourseRow
	err := row.Scan(
		&i.Enrollmentid,
		&i.Userid,
		&i.Courseid,
		&i.Roleid,
		&i.Batchid,
		&i.Rolename,
	)
	return i, err
}

const unenrollUser = `-- name: UnenrollUser :exec
DELETE FROM Enrollment
WHERE UserID = ? AND CourseID = ?
`

type UnenrollUserParams struct {
	Userid   int32 `json:"userid"`
	Courseid int32 `json:"courseid"`
}

func (q *Queries) UnenrollUser(ctx context.Context, arg UnenrollUserParams) error {
	_, err := q.db.ExecContext(ctx, unenrollUser, arg.Userid, arg.Courseid)
	return err
}

const updateEnrollmentBatch = `-- name: UpdateEnrollmentBatch :exec
UPDATE Enrollment
SET BatchID = ?
WHERE EnrollmentID = ?
`

type UpdateEnrollmentBatchParams struct {
	Batchid      sql.NullInt32 `json:"batchid"`
	Enrollmentid int32         `json:"enrollmentid"`
}

func (q *Queries) UpdateEnrollmentBatch(ctx context.Context, arg UpdateEnrollmentBatchParams) error {
	_, err := q.db.ExecContext(ctx, updateEnrollmentBatch, arg.Batchid, arg.Enrollmentid)
	return err
}
