// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Answer struct {
	Answerid         int32         `json:"answerid"`
	Body             string        `json:"body"`
	Upvotes          sql.NullInt32 `json:"upvotes"`
	Isofficialanswer sql.NullBool  `json:"isofficialanswer"`
	Createdat        sql.NullTime  `json:"createdat"`
	Questionid       int32         `json:"questionid"`
	Userid           int32         `json:"userid"`
}

type Answerupvote struct {
	Answerid int32 `json:"answerid"`
	Userid   int32 `json:"userid"`
}

type Assignment struct {
	Assignmentid   int32          `json:"assignmentid"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Deadline       time.Time      `json:"deadline"`
	Formatrequired sql.NullString `json:"formatrequired"`
	Courseid       int32          `json:"courseid"`
	Rubricid       sql.NullInt32  `json:"rubricid"`
}

type Attendance struct {
	Sessionid int32  `json:"sessionid"`
	Userid    int32  `json:"userid"`
	Status    string `json:"status"`
}

type Batch struct {
	Batchid   int32  `json:"batchid"`
	Batchname string `json:"batchname"`
	Courseid  int32  `json:"courseid"`
}

type Classsession struct {
	Sessionid    int32          `json:"sessionid"`
	Starttime    time.Time      `json:"starttime"`
	Endtime      time.Time      `json:"endtime"`
	Roomlocation sql.NullString `json:"roomlocation"`
	Batchid      int32          `json:"batchid"`
}

type Course struct {
	Courseid    int32          `json:"courseid"`
	Coursecode  string         `json:"coursecode"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

type Enrollment struct {
	Enrollmentid int32         `json:"enrollmentid"`
	Userid       int32         `json:"userid"`
	Courseid     int32         `json:"courseid"`
	Roleid       int32         `json:"roleid"`
	Batchid      sql.NullInt32 `json:"batchid"`
}

type Evaluation struct {
	Submissionid int32          `json:"submissionid"`
	Score        string         `json:"score"`
	Feedback     sql.NullString `json:"feedback"`
	Userid       int32          `json:"userid"`
}

type Notification struct {
	Notificationid int32          `json:"notificationid"`
	Message        string         `json:"message"`
	Type           sql.NullString `json:"type"`
	Isread         sql.NullBool   `json:"isread"`
	Createdat      sql.NullTime   `json:"createdat"`
	Userid         int32          `json:"userid"`
}

type Prerequisite struct {
	Courseid         int32          `json:"courseid"`
	Requiredcourseid int32          `json:"requiredcourseid"`
	Minpassinggrade  sql.NullString `json:"minpassinggrade"`
}

type Question struct {
	Questionid int32        `json:"questionid"`
	Title      string       `json:"title"`
	Body       string       `json:"body"`
	Createdat  sql.NullTime `json:"createdat"`
	Courseid   int32        `json:"courseid"`
	Userid     int32        `json:"userid"`
}

type Resource struct {
	Resourceid int32        `json:"resourceid"`
	Title      string       `json:"title"`
	Fileurl    string       `json:"fileurl"`
	Uploadedat sql.NullTime `json:"uploadedat"`
	Categoryid int32        `json:"categoryid"`
}

type Resourcecategory struct {
	Categoryid   int32  `json:"categoryid"`
	Categoryname string `json:"categoryname"`
	Courseid     int32  `json:"courseid"`
}

type Role struct {
	Roleid   int32  `json:"roleid"`
	Rolename string `json:"rolename"`
}

type Rubric struct {
	Rubricid    int32          `json:"rubricid"`
	Title       string         `json:"title"`
	Department  sql.NullString `json:"department"`
	Description sql.NullString `json:"description"`
}

type Submission struct {
	Submissionid   int32        `json:"submissionid"`
	Submissiontime sql.NullTime `json:"submissiontime"`
	Contentdata    string       `json:"contentdata"`
	Assignmentid   int32        `json:"assignmentid"`
	Userid         int32        `json:"userid"`
}

type User struct {
	Userid       int32          `json:"userid"`
	Firstname    string         `json:"firstname"`
	Lastname     string         `json:"lastname"`
	Email        string         `json:"email"`
	Passwordhash string         `json:"passwordhash"`
	Bio          sql.NullString `json:"bio"`
	Githublink   sql.NullString `json:"githublink"`
	Linkedinlink sql.NullString `json:"linkedinlink"`
}

type Userphoto struct {
	Userid   sql.NullInt32  `json:"userid"`
	Photourl sql.NullString `json:"photourl"`
}
