// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :execresult
INSERT INTO Notification (Message, Type, IsRead, CreatedAt, UserID)
VALUES (?, ?, FALSE, NOW(), ?)
`

type CreateNotificationParams struct {
	Message string         `json:"message"`
	Type    sql.NullString `json:"type"`
	Userid  int32          `json:"userid"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotification, arg.Message, arg.Type, arg.Userid)
}

const getUnreadNotificationsCount = `-- name: GetUnreadNotificationsCount :one
SELECT COUNT(*) AS UnreadCount
FROM Notification
WHERE UserID = ? AND IsRead = FALSE
`

func (q *Queries) GetUnreadNotificationsCount(ctx context.Context, userid int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationsCount, userid)
	var unreadcount int64
	err := row.Scan(&unreadcount)
	return unreadcount, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT NotificationID, Message, Type, IsRead, CreatedAt, UserID
FROM Notification
WHERE UserID = ?
ORDER BY CreatedAt DESC
LIMIT 50
`

func (q *Queries) GetUserNotifications(ctx context.Context, userid int32) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotifications, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.Notificationid,
			&i.Message,
			&i.Type,
			&i.Isread,
			&i.Createdat,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE Notification
SET IsRead = TRUE
WHERE UserID = ?
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userid int32) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userid)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE Notification
SET IsRead = TRUE
WHERE NotificationID = ? AND UserID = ?
`

type MarkNotificationAsReadParams struct {
	Notificationid int32 `json:"notificationid"`
	Userid         int32 `json:"userid"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, arg.Notificationid, arg.Userid)
	return err
}
