// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package db

import (
	"context"
	"database/sql"
)

const addAnswerUpvote = `-- name: AddAnswerUpvote :exec
INSERT INTO AnswerUpvote (AnswerID, UserID)
VALUES (?, ?)
`

type AddAnswerUpvoteParams struct {
	Answerid int32 `json:"answerid"`
	Userid   int32 `json:"userid"`
}

func (q *Queries) AddAnswerUpvote(ctx context.Context, arg AddAnswerUpvoteParams) error {
	_, err := q.db.ExecContext(ctx, addAnswerUpvote, arg.Answerid, arg.Userid)
	return err
}

const createAnswer = `-- name: CreateAnswer :execresult
INSERT INTO Answer (Body, QuestionID, UserID)
VALUES (?, ?, ?)
`

type CreateAnswerParams struct {
	Body       string `json:"body"`
	Questionid int32  `json:"questionid"`
	Userid     int32  `json:"userid"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAnswer, arg.Body, arg.Questionid, arg.Userid)
}

const createQuestion = `-- name: CreateQuestion :execresult
INSERT INTO Question (Title, Body, CourseID, UserID)
VALUES (?, ?, ?, ?)
`

type CreateQuestionParams struct {
	Title    string `json:"title"`
	Body     string `json:"body"`
	Courseid int32  `json:"courseid"`
	Userid   int32  `json:"userid"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createQuestion,
		arg.Title,
		arg.Body,
		arg.Courseid,
		arg.Userid,
	)
}

const decrementAnswerUpvotes = `-- name: DecrementAnswerUpvotes :exec
UPDATE Answer SET Upvotes = GREATEST(Upvotes - 1, 0)
WHERE AnswerID = ?
`

func (q *Queries) DecrementAnswerUpvotes(ctx context.Context, answerid int32) error {
	_, err := q.db.ExecContext(ctx, decrementAnswerUpvotes, answerid)
	return err
}

const getAnswerByID = `-- name: GetAnswerByID :one
SELECT a.AnswerID, a.Body, a.Upvotes, a.IsOfficialAnswer, a.QuestionID, a.UserID,
       q.CourseID
FROM Answer a
JOIN Question q ON a.QuestionID = q.QuestionID
WHERE a.AnswerID = ? LIMIT 1
`

type GetAnswerByIDRow struct {
	Answerid         int32         `json:"answerid"`
	Body             string        `json:"body"`
	Upvotes          sql.NullInt32 `json:"upvotes"`
	Isofficialanswer sql.NullBool  `json:"isofficialanswer"`
	Questionid       int32         `json:"questionid"`
	Userid           int32         `json:"userid"`
	Courseid         int32         `json:"courseid"`
}

func (q *Queries) GetAnswerByID(ctx context.Context, answerid int32) (GetAnswerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAnswerByID, answerid)
	var i GetAnswerByIDRow
	err := row.Scan(
		&i.Answerid,
		&i.Body,
		&i.Upvotes,
		&i.Isofficialanswer,
		&i.Questionid,
		&i.Userid,
		&i.Courseid,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT q.QuestionID, q.Title, q.Body, q.CreatedAt, q.CourseID, q.UserID,
       u.FirstName, u.LastName, u.Email
FROM Question q
JOIN User u ON q.UserID = u.UserID
WHERE q.QuestionID = ? LIMIT 1
`

type GetQuestionByIDRow struct {
	Questionid int32        `json:"questionid"`
	Title      string       `json:"title"`
	Body       string       `json:"body"`
	Createdat  sql.NullTime `json:"createdat"`
	Courseid   int32        `json:"courseid"`
	Userid     int32        `json:"userid"`
	Firstname  string       `json:"firstname"`
	Lastname   string       `json:"lastname"`
	Email      string       `json:"email"`
}

func (q *Queries) GetQuestionByID(ctx context.Context, questionid int32) (GetQuestionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, questionid)
	var i GetQuestionByIDRow
	err := row.Scan(
		&i.Questionid,
		&i.Title,
		&i.Body,
		&i.Createdat,
		&i.Courseid,
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
	)
	return i, err
}

const hasAnswerUpvote = `-- name: HasAnswerUpvote :one
SELECT COUNT(*) FROM AnswerUpvote
WHERE AnswerID = ? AND UserID = ?
`

type HasAnswerUpvoteParams struct {
	Answerid int32 `json:"answerid"`
	Userid   int32 `json:"userid"`
}

func (q *Queries) HasAnswerUpvote(ctx context.Context, arg HasAnswerUpvoteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAnswerUpvote, arg.Answerid, arg.Userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementAnswerUpvotes = `-- name: IncrementAnswerUpvotes :exec
UPDATE Answer SET Upvotes = Upvotes + 1
WHERE AnswerID = ?
`

func (q *Queries) IncrementAnswerUpvotes(ctx context.Context, answerid int32) error {
	_, err := q.db.ExecContext(ctx, incrementAnswerUpvotes, answerid)
	return err
}

const listAnswersByQuestion = `-- name: ListAnswersByQuestion :many
SELECT a.AnswerID, a.Body, a.Upvotes, a.IsOfficialAnswer, a.CreatedAt, a.QuestionID, a.UserID,
       u.FirstName, u.LastName, u.Email,
       r.RoleName AS UserRole,
       EXISTS(SELECT 1 FROM AnswerUpvote au WHERE au.AnswerID = a.AnswerID AND au.UserID = ?) AS HasUpvoted
FROM Answer a
JOIN User u ON a.UserID = u.UserID
JOIN Question q ON a.QuestionID = q.QuestionID
LEFT JOIN Enrollment e ON (e.UserID = a.UserID AND e.CourseID = q.CourseID)
LEFT JOIN Role r ON e.RoleID = r.RoleID
WHERE a.QuestionID = ?
ORDER BY a.IsOfficialAnswer DESC, a.Upvotes DESC, a.CreatedAt ASC
`

type ListAnswersByQuestionParams struct {
	Userid     int32 `json:"userid"`
	Questionid int32 `json:"questionid"`
}

type ListAnswersByQuestionRow struct {
	Answerid         int32          `json:"answerid"`
	Body             string         `json:"body"`
	Upvotes          sql.NullInt32  `json:"upvotes"`
	Isofficialanswer sql.NullBool   `json:"isofficialanswer"`
	Createdat        sql.NullTime   `json:"createdat"`
	Questionid       int32          `json:"questionid"`
	Userid           int32          `json:"userid"`
	Firstname        string         `json:"firstname"`
	Lastname         string         `json:"lastname"`
	Email            string         `json:"email"`
	Userrole         sql.NullString `json:"userrole"`
	Hasupvoted       bool           `json:"hasupvoted"`
}

func (q *Queries) ListAnswersByQuestion(ctx context.Context, arg ListAnswersByQuestionParams) ([]ListAnswersByQuestionRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersByQuestion, arg.Userid, arg.Questionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnswersByQuestionRow{}
	for rows.Next() {
		var i ListAnswersByQuestionRow
		if err := rows.Scan(
			&i.Answerid,
			&i.Body,
			&i.Upvotes,
			&i.Isofficialanswer,
			&i.Createdat,
			&i.Questionid,
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Userrole,
			&i.Hasupvoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByCourse = `-- name: ListQuestionsByCourse :many
SELECT q.QuestionID, q.Title, q.Body, q.CreatedAt, q.CourseID, q.UserID,
       u.FirstName, u.LastName,
       COUNT(a.AnswerID) AS AnswerCount,
       MAX(CASE WHEN a.IsOfficialAnswer = TRUE THEN 1 ELSE 0 END) AS HasOfficialAnswer
FROM Question q
JOIN User u ON q.UserID = u.UserID
LEFT JOIN Answer a ON q.QuestionID = a.QuestionID
WHERE q.CourseID = ?
GROUP BY q.QuestionID, q.Title, q.Body, q.CreatedAt, q.CourseID, q.UserID, u.FirstName, u.LastName
ORDER BY q.CreatedAt DESC
`

type ListQuestionsByCourseRow struct {
	Questionid        int32        `json:"questionid"`
	Title             string       `json:"title"`
	Body              string       `json:"body"`
	Createdat         sql.NullTime `json:"createdat"`
	Courseid          int32        `json:"courseid"`
	Userid            int32        `json:"userid"`
	Firstname         string       `json:"firstname"`
	Lastname          string       `json:"lastname"`
	Answercount       int64        `json:"answercount"`
	Hasofficialanswer interface{}  `json:"hasofficialanswer"`
}

func (q *Queries) ListQuestionsByCourse(ctx context.Context, courseid int32) ([]ListQuestionsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsByCourseRow{}
	for rows.Next() {
		var i ListQuestionsByCourseRow
		if err := rows.Scan(
			&i.Questionid,
			&i.Title,
			&i.Body,
			&i.Createdat,
			&i.Courseid,
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.Answercount,
			&i.Hasofficialanswer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOfficialAnswer = `-- name: MarkOfficialAnswer :exec
UPDATE Answer
SET IsOfficialAnswer = ?
WHERE AnswerID = ?
`

type MarkOfficialAnswerParams struct {
	Isofficialanswer sql.NullBool `json:"isofficialanswer"`
	Answerid         int32        `json:"answerid"`
}

func (q *Queries) MarkOfficialAnswer(ctx context.Context, arg MarkOfficialAnswerParams) error {
	_, err := q.db.ExecContext(ctx, markOfficialAnswer, arg.Isofficialanswer, arg.Answerid)
	return err
}

const removeAnswerUpvote = `-- name: RemoveAnswerUpvote :exec
DELETE FROM AnswerUpvote
WHERE AnswerID = ? AND UserID = ?
`

type RemoveAnswerUpvoteParams struct {
	Answerid int32 `json:"answerid"`
	Userid   int32 `json:"userid"`
}

func (q *Queries) RemoveAnswerUpvote(ctx context.Context, arg RemoveAnswerUpvoteParams) error {
	_, err := q.db.ExecContext(ctx, removeAnswerUpvote, arg.Answerid, arg.Userid)
	return err
}
