// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :execresult
INSERT INTO ResourceCategory (CategoryName, CourseID)
VALUES (?, ?)
`

type CreateCategoryParams struct {
	Categoryname string `json:"categoryname"`
	Courseid     int32  `json:"courseid"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategory, arg.Categoryname, arg.Courseid)
}

const createResource = `-- name: CreateResource :execresult
INSERT INTO Resource (Title, FileURL, UploadedAt, CategoryID)
VALUES (?, ?, NOW(), ?)
`

type CreateResourceParams struct {
	Title      string `json:"title"`
	Fileurl    string `json:"fileurl"`
	Categoryid int32  `json:"categoryid"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createResource, arg.Title, arg.Fileurl, arg.Categoryid)
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM Resource WHERE ResourceID = ?
`

func (q *Queries) DeleteResource(ctx context.Context, resourceid int32) error {
	_, err := q.db.ExecContext(ctx, deleteResource, resourceid)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT CategoryID, CategoryName, CourseID
FROM ResourceCategory
WHERE CategoryID = ? LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, categoryid int32) (Resourcecategory, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, categoryid)
	var i Resourcecategory
	err := row.Scan(&i.Categoryid, &i.Categoryname, &i.Courseid)
	return i, err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT r.ResourceID, r.Title, r.FileURL, r.UploadedAt, r.CategoryID, c.CourseID
FROM Resource r
JOIN ResourceCategory c ON r.CategoryID = c.CategoryID
WHERE r.ResourceID = ? LIMIT 1
`

type GetResourceByIDRow struct {
	Resourceid int32        `json:"resourceid"`
	Title      string       `json:"title"`
	Fileurl    string       `json:"fileurl"`
	Uploadedat sql.NullTime `json:"uploadedat"`
	Categoryid int32        `json:"categoryid"`
	Courseid   int32        `json:"courseid"`
}

func (q *Queries) GetResourceByID(ctx context.Context, resourceid int32) (GetResourceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceByID, resourceid)
	var i GetResourceByIDRow
	err := row.Scan(
		&i.Resourceid,
		&i.Title,
		&i.Fileurl,
		&i.Uploadedat,
		&i.Categoryid,
		&i.Courseid,
	)
	return i, err
}

const listCategoriesByCourse = `-- name: ListCategoriesByCourse :many
SELECT CategoryID, CategoryName, CourseID
FROM ResourceCategory
WHERE CourseID = ?
ORDER BY CategoryName ASC
`

func (q *Queries) ListCategoriesByCourse(ctx context.Context, courseid int32) ([]Resourcecategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resourcecategory{}
	for rows.Next() {
		var i Resourcecategory
		if err := rows.Scan(&i.Categoryid, &i.Categoryname, &i.Courseid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCategory = `-- name: ListResourcesByCategory :many
SELECT ResourceID, Title, FileURL, UploadedAt, CategoryID
FROM Resource
WHERE CategoryID = ?
ORDER BY UploadedAt DESC
`

func (q *Queries) ListResourcesByCategory(ctx context.Context, categoryid int32) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCategory, categoryid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.Resourceid,
			&i.Title,
			&i.Fileurl,
			&i.Uploadedat,
			&i.Categoryid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCourse = `-- name: ListResourcesByCourse :many
SELECT r.ResourceID, r.Title, r.FileURL, r.UploadedAt, r.CategoryID,
       c.CategoryName
FROM Resource r
JOIN ResourceCategory c ON r.CategoryID = c.CategoryID
WHERE c.CourseID = ?
ORDER BY c.CategoryName ASC, r.UploadedAt DESC
`

type ListResourcesByCourseRow struct {
	Resourceid   int32        `json:"resourceid"`
	Title        string       `json:"title"`
	Fileurl      string       `json:"fileurl"`
	Uploadedat   sql.NullTime `json:"uploadedat"`
	Categoryid   int32        `json:"categoryid"`
	Categoryname string       `json:"categoryname"`
}

func (q *Queries) ListResourcesByCourse(ctx context.Context, courseid int32) ([]ListResourcesByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCourse, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesByCourseRow{}
	for rows.Next() {
		var i ListResourcesByCourseRow
		if err := rows.Scan(
			&i.Resourceid,
			&i.Title,
			&i.Fileurl,
			&i.Uploadedat,
			&i.Categoryid,
			&i.Categoryname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
