// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rubrics.sql

package db

import (
	"context"
	"database/sql"
)

const createRubric = `-- name: CreateRubric :execresult
INSERT INTO Rubric (Title, Department, Description)
VALUES (?, ?, ?)
`

type CreateRubricParams struct {
	Title       string         `json:"title"`
	Department  sql.NullString `json:"department"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateRubric(ctx context.Context, arg CreateRubricParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRubric, arg.Title, arg.Department, arg.Description)
}

const getRubricByID = `-- name: GetRubricByID :one
SELECT RubricID, Title, Department, Description
FROM Rubric
WHERE RubricID = ? LIMIT 1
`

func (q *Queries) GetRubricByID(ctx context.Context, rubricid int32) (Rubric, error) {
	row := q.db.QueryRowContext(ctx, getRubricByID, rubricid)
	var i Rubric
	err := row.Scan(
		&i.Rubricid,
		&i.Title,
		&i.Department,
		&i.Description,
	)
	return i, err
}

const listRubrics = `-- name: ListRubrics :many
SELECT RubricID, Title, Department, Description
FROM Rubric
ORDER BY Title ASC
`

func (q *Queries) ListRubrics(ctx context.Context) ([]Rubric, error) {
	rows, err := q.db.QueryContext(ctx, listRubrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rubric{}
	for rows.Next() {
		var i Rubric
		if err := rows.Scan(
			&i.Rubricid,
			&i.Title,
			&i.Department,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRubric = `-- name: UpdateRubric :exec
UPDATE Rubric
SET Title = ?, Department = ?, Description = ?
WHERE RubricID = ?
`

type UpdateRubricParams struct {
	Title       string         `json:"title"`
	Department  sql.NullString `json:"department"`
	Description sql.NullString `json:"description"`
	Rubricid    int32          `json:"rubricid"`
}

func (q *Queries) UpdateRubric(ctx context.Context, arg UpdateRubricParams) error {
	_, err := q.db.ExecContext(ctx, updateRubric,
		arg.Title,
		arg.Department,
		arg.Description,
		arg.Rubricid,
	)
	return err
}
