// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createOrUpdateEvaluation = `-- name: CreateOrUpdateEvaluation :exec
INSERT INTO Evaluation (SubmissionID, Score, Feedback, UserID)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE Score = VALUES(Score), Feedback = VALUES(Feedback), UserID = VALUES(UserID)
`

type CreateOrUpdateEvaluationParams struct {
	Submissionid int32          `json:"submissionid"`
	Score        string         `json:"score"`
	Feedback     sql.NullString `json:"feedback"`
	Userid       int32          `json:"userid"`
}

func (q *Queries) CreateOrUpdateEvaluation(ctx context.Context, arg CreateOrUpdateEvaluationParams) error {
	_, err := q.db.ExecContext(ctx, createOrUpdateEvaluation,
		arg.Submissionid,
		arg.Score,
		arg.Feedback,
		arg.Userid,
	)
	return err
}

const createSubmission = `-- name: CreateSubmission :execresult
INSERT INTO Submission (SubmissionTime, ContentData, AssignmentID, UserID)
VALUES (NOW(), ?, ?, ?)
`

type CreateSubmissionParams struct {
	Contentdata  string `json:"contentdata"`
	Assignmentid int32  `json:"assignmentid"`
	Userid       int32  `json:"userid"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSubmission, arg.Contentdata, arg.Assignmentid, arg.Userid)
}

const getStudentGradesInCourse = `-- name: GetStudentGradesInCourse :many
SELECT 
    u.FirstName, 
    a.AssignmentID,
    a.Title AS Assignment, 
    e.Score, 
    e.Feedback
FROM User u
JOIN Submission s ON u.UserID = s.UserID
JOIN Assignment a ON s.AssignmentID = a.AssignmentID
JOIN Evaluation e ON s.SubmissionID = e.SubmissionID
WHERE u.UserID = ? AND a.CourseID = ?
`

type GetStudentGradesInCourseParams struct {
	Userid   int32 `json:"userid"`
	Courseid int32 `json:"courseid"`
}

type GetStudentGradesInCourseRow struct {
	Firstname    string         `json:"firstname"`
	Assignmentid int32          `json:"assignmentid"`
	Assignment   string         `json:"assignment"`
	Score        string         `json:"score"`
	Feedback     sql.NullString `json:"feedback"`
}

// Case Study Query 1: Assignment scores and feedback for student
func (q *Queries) GetStudentGradesInCourse(ctx context.Context, arg GetStudentGradesInCourseParams) ([]GetStudentGradesInCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentGradesInCourse, arg.Userid, arg.Courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentGradesInCourseRow{}
	for rows.Next() {
		var i GetStudentGradesInCourseRow
		if err := rows.Scan(
			&i.Firstname,
			&i.Assignmentid,
			&i.Assignment,
			&i.Score,
			&i.Feedback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT s.SubmissionID, s.SubmissionTime, s.ContentData, s.AssignmentID, s.UserID,
       u.FirstName, u.LastName, u.Email,
       a.Title AS AssignmentTitle, a.Deadline, a.CourseID,
       e.Score, e.Feedback, e.UserID AS GradedByUserID
FROM Submission s
JOIN User u ON s.UserID = u.UserID
JOIN Assignment a ON s.AssignmentID = a.AssignmentID
LEFT JOIN Evaluation e ON s.SubmissionID = e.SubmissionID
WHERE s.SubmissionID = ? LIMIT 1
`

type GetSubmissionByIDRow struct {
	Submissionid    int32          `json:"submissionid"`
	Submissiontime  sql.NullTime   `json:"submissiontime"`
	Contentdata     string         `json:"contentdata"`
	Assignmentid    int32          `json:"assignmentid"`
	Userid          int32          `json:"userid"`
	Firstname       string         `json:"firstname"`
	Lastname        string         `json:"lastname"`
	Email           string         `json:"email"`
	Assignmenttitle string         `json:"assignmenttitle"`
	Deadline        time.Time      `json:"deadline"`
	Courseid        int32          `json:"courseid"`
	Score           sql.NullString `json:"score"`
	Feedback        sql.NullString `json:"feedback"`
	Gradedbyuserid  sql.NullInt32  `json:"gradedbyuserid"`
}

func (q *Queries) GetSubmissionByID(ctx context.Context, submissionid int32) (GetSubmissionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByID, submissionid)
	var i GetSubmissionByIDRow
	err := row.Scan(
		&i.Submissionid,
		&i.Submissiontime,
		&i.Contentdata,
		&i.Assignmentid,
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Assignmenttitle,
		&i.Deadline,
		&i.Courseid,
		&i.Score,
		&i.Feedback,
		&i.Gradedbyuserid,
	)
	return i, err
}

const getSubmissionReport = `-- name: GetSubmissionReport :many
SELECT 
    a.AssignmentID,
    a.Title AS AssignmentName,
    CONCAT(Student.FirstName, ' ', Student.LastName) AS StudentName,
    s.SubmissionID,
    s.SubmissionTime,
    a.Deadline,
    CASE 
        WHEN s.SubmissionTime > a.Deadline THEN 'LATE'
        ELSE 'ON TIME'
    END AS Timeliness,
    e.Score,
    CAST(IFNULL(CONCAT(Grader.FirstName, ' ', Grader.LastName), 'Ungraded') AS CHAR(200)) AS GradedBy
FROM Submission s
JOIN Assignment a ON s.AssignmentID = a.AssignmentID
JOIN User Student ON s.UserID = Student.UserID
LEFT JOIN Evaluation e ON s.SubmissionID = e.SubmissionID
LEFT JOIN User Grader ON e.UserID = Grader.UserID
WHERE a.CourseID = ?
ORDER BY e.Score DESC
`

type GetSubmissionReportRow struct {
	Assignmentid   int32          `json:"assignmentid"`
	Assignmentname string         `json:"assignmentname"`
	Studentname    string         `json:"studentname"`
	Submissionid   int32          `json:"submissionid"`
	Submissiontime sql.NullTime   `json:"submissiontime"`
	Deadline       time.Time      `json:"deadline"`
	Timeliness     string         `json:"timeliness"`
	Score          sql.NullString `json:"score"`
	Gradedby       interface{}    `json:"gradedby"`
}

// Case Study Query 3: Full submission report with timeliness and grader details
func (q *Queries) GetSubmissionReport(ctx context.Context, courseid int32) ([]GetSubmissionReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubmissionReport, courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubmissionReportRow{}
	for rows.Next() {
		var i GetSubmissionReportRow
		if err := rows.Scan(
			&i.Assignmentid,
			&i.Assignmentname,
			&i.Studentname,
			&i.Submissionid,
			&i.Submissiontime,
			&i.Deadline,
			&i.Timeliness,
			&i.Score,
			&i.Gradedby,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubmissionForAssignment = `-- name: GetUserSubmissionForAssignment :one
SELECT s.SubmissionID, s.SubmissionTime, s.ContentData, s.AssignmentID, s.UserID,
       e.Score, e.Feedback, e.UserID AS GradedByUserID
FROM Submission s
LEFT JOIN Evaluation e ON s.SubmissionID = e.SubmissionID
WHERE s.AssignmentID = ? AND s.UserID = ?
LIMIT 1
`

type GetUserSubmissionForAssignmentParams struct {
	Assignmentid int32 `json:"assignmentid"`
	Userid       int32 `json:"userid"`
}

type GetUserSubmissionForAssignmentRow struct {
	Submissionid   int32          `json:"submissionid"`
	Submissiontime sql.NullTime   `json:"submissiontime"`
	Contentdata    string         `json:"contentdata"`
	Assignmentid   int32          `json:"assignmentid"`
	Userid         int32          `json:"userid"`
	Score          sql.NullString `json:"score"`
	Feedback       sql.NullString `json:"feedback"`
	Gradedbyuserid sql.NullInt32  `json:"gradedbyuserid"`
}

func (q *Queries) GetUserSubmissionForAssignment(ctx context.Context, arg GetUserSubmissionForAssignmentParams) (GetUserSubmissionForAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSubmissionForAssignment, arg.Assignmentid, arg.Userid)
	var i GetUserSubmissionForAssignmentRow
	err := row.Scan(
		&i.Submissionid,
		&i.Submissiontime,
		&i.Contentdata,
		&i.Assignmentid,
		&i.Userid,
		&i.Score,
		&i.Feedback,
		&i.Gradedbyuserid,
	)
	return i, err
}

const listSubmissionsByAssignment = `-- name: ListSubmissionsByAssignment :many
SELECT s.SubmissionID, s.SubmissionTime, s.ContentData, s.AssignmentID, s.UserID,
       u.FirstName, u.LastName, u.Email,
       e.Score, e.Feedback,
       CASE 
           WHEN s.SubmissionTime > a.Deadline THEN 'LATE'
           ELSE 'ON TIME'
       END AS Timeliness
FROM Submission s
JOIN User u ON s.UserID = u.UserID
JOIN Assignment a ON s.AssignmentID = a.AssignmentID
LEFT JOIN Evaluation e ON s.SubmissionID = e.SubmissionID
WHERE s.AssignmentID = ?
ORDER BY s.SubmissionTime DESC
`

type ListSubmissionsByAssignmentRow struct {
	Submissionid   int32          `json:"submissionid"`
	Submissiontime sql.NullTime   `json:"submissiontime"`
	Contentdata    string         `json:"contentdata"`
	Assignmentid   int32          `json:"assignmentid"`
	Userid         int32          `json:"userid"`
	Firstname      string         `json:"firstname"`
	Lastname       string         `json:"lastname"`
	Email          string         `json:"email"`
	Score          sql.NullString `json:"score"`
	Feedback       sql.NullString `json:"feedback"`
	Timeliness     string         `json:"timeliness"`
}

func (q *Queries) ListSubmissionsByAssignment(ctx context.Context, assignmentid int32) ([]ListSubmissionsByAssignmentRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByAssignment, assignmentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsByAssignmentRow{}
	for rows.Next() {
		var i ListSubmissionsByAssignmentRow
		if err := rows.Scan(
			&i.Submissionid,
			&i.Submissiontime,
			&i.Contentdata,
			&i.Assignmentid,
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Score,
			&i.Feedback,
			&i.Timeliness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
