// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const addUserPhoto = `-- name: AddUserPhoto :exec
INSERT INTO UserPhoto (UserID, PhotoURL) VALUES (?, ?)
`

type AddUserPhotoParams struct {
	Userid   sql.NullInt32  `json:"userid"`
	Photourl sql.NullString `json:"photourl"`
}

func (q *Queries) AddUserPhoto(ctx context.Context, arg AddUserPhotoParams) error {
	_, err := q.db.ExecContext(ctx, addUserPhoto, arg.Userid, arg.Photourl)
	return err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO User (FirstName, LastName, Email, PasswordHash, Bio, GitHubLink, LinkedInLink)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Firstname    string         `json:"firstname"`
	Lastname     string         `json:"lastname"`
	Email        string         `json:"email"`
	Passwordhash string         `json:"passwordhash"`
	Bio          sql.NullString `json:"bio"`
	Githublink   sql.NullString `json:"githublink"`
	Linkedinlink sql.NullString `json:"linkedinlink"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Passwordhash,
		arg.Bio,
		arg.Githublink,
		arg.Linkedinlink,
	)
}

const deleteUserPhoto = `-- name: DeleteUserPhoto :exec
DELETE FROM UserPhoto WHERE UserID = ? AND PhotoURL = ?
`

type DeleteUserPhotoParams struct {
	Userid   sql.NullInt32  `json:"userid"`
	Photourl sql.NullString `json:"photourl"`
}

func (q *Queries) DeleteUserPhoto(ctx context.Context, arg DeleteUserPhotoParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserPhoto, arg.Userid, arg.Photourl)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT UserID, FirstName, LastName, Email, PasswordHash, Bio, GitHubLink, LinkedInLink
FROM User
WHERE Email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Passwordhash,
		&i.Bio,
		&i.Githublink,
		&i.Linkedinlink,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT UserID, FirstName, LastName, Email, PasswordHash, Bio, GitHubLink, LinkedInLink
FROM User
WHERE UserID = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userid int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Passwordhash,
		&i.Bio,
		&i.Githublink,
		&i.Linkedinlink,
	)
	return i, err
}

const getUserPhotos = `-- name: GetUserPhotos :many
SELECT PhotoURL FROM UserPhoto WHERE UserID = ?
`

func (q *Queries) GetUserPhotos(ctx context.Context, userid sql.NullInt32) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getUserPhotos, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var photourl sql.NullString
		if err := rows.Scan(&photourl); err != nil {
			return nil, err
		}
		items = append(items, photourl)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT UserID, FirstName, LastName, Email, Bio, GitHubLink, LinkedInLink
FROM User
ORDER BY UserID ASC
`

type ListUsersRow struct {
	Userid       int32          `json:"userid"`
	Firstname    string         `json:"firstname"`
	Lastname     string         `json:"lastname"`
	Email        string         `json:"email"`
	Bio          sql.NullString `json:"bio"`
	Githublink   sql.NullString `json:"githublink"`
	Linkedinlink sql.NullString `json:"linkedinlink"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.Userid,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Bio,
			&i.Githublink,
			&i.Linkedinlink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE User
SET FirstName = ?, LastName = ?, Bio = ?, GitHubLink = ?, LinkedInLink = ?
WHERE UserID = ?
`

type UpdateUserProfileParams struct {
	Firstname    string         `json:"firstname"`
	Lastname     string         `json:"lastname"`
	Bio          sql.NullString `json:"bio"`
	Githublink   sql.NullString `json:"githublink"`
	Linkedinlink sql.NullString `json:"linkedinlink"`
	Userid       int32          `json:"userid"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Firstname,
		arg.Lastname,
		arg.Bio,
		arg.Githublink,
		arg.Linkedinlink,
		arg.Userid,
	)
	return err
}
